import os

WINDOW_WIDTH, WINDOW_HEIGHT = 1280, 720

BOARD_REGION_WIDTH = 720
BOARD_REGION_HEIGHT = 720
RIGHT_PANEL_X = BOARD_REGION_WIDTH
RIGHT_PANEL_WIDTH = WINDOW_WIDTH - BOARD_REGION_WIDTH
RIGHT_PANEL_HEIGHT = WINDOW_HEIGHT

PUZZLE_PADDING = 20
PUZZLE_SIZE = BOARD_REGION_WIDTH - 2 * PUZZLE_PADDING  
TILE_SIZE = PUZZLE_SIZE // 3                            

PUZZLE_OFFSET_X = PUZZLE_PADDING
PUZZLE_OFFSET_Y = PUZZLE_PADDING

FPS = 90
ANIM_DURATION_MS = 300    
FADE_SPEED = 15           

COLOR_BG = (30, 30, 30)
COLOR_PANEL = (40, 40, 40)
COLOR_HIGHLIGHT = (70, 70, 70)
COLOR_TEXT = (220, 220, 220)
COLOR_BUTTON = (60, 60, 60)
COLOR_BUTTON_HOVER = (100, 100, 100)

TEMPLATE_DIR = "assets/templates"

ALL_TEMPLATE_FILES = [
    os.path.join(TEMPLATE_DIR, fname)
    for fname in sorted(os.listdir(TEMPLATE_DIR))
    if fname.lower().endswith((".png", ".jpg", ".jpeg"))
][:5]  

IMAGE_THUMB_SIZE = 80   
THUMBS_PER_ROW = 5      
THUMBS_SPACING = 10     

CHECKBOX_SIZE = 20
CHECKBOX_X = RIGHT_PANEL_X + 20
CHECKBOX_Y = WINDOW_HEIGHT - 60
LABEL_X = CHECKBOX_X + CHECKBOX_SIZE + 10
LABEL_Y = CHECKBOX_Y - 2

ALGORITHMS = ["BFS", "DFS", "A*", "Dijkstra"]
